name: Build

on:
  push:
    branches: [ algoxy ]
  pull_request:
    branches: [ algoxy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make imagemagick graphviz
            make
      - name: Upload algoxy-en.pdf
        uses: actions/upload-artifact@v2
        with:
          path: algoxy-en.pdf
      - name: Upload algoxy-zh-cn.pdf
        uses: actions/upload-artifact@v2
        with:
          path: algoxy-zh-cn.pdf
